### ISSUE TITLE
HorseStats 1.1 incompatible with Tabuucore 2.7.0

### ISSUE THREAD

**Issue by TheoLegendSmyth** [MrCrackerplays/HorseStats#2]
Horse stats returns the following error in Minecraft JE 1.20.1 when running with the latest Tabuucore :
 Error: Using an older version of TabuuCore than required. Use TabuuCore version 2020.4.5 or higher!

**To Reproduce**
1. Install Horsestats in Minecraft JE Server 1.20.1 plugins folder.
2. Install TabuuCore in Minecraft JE Server 1.20.1 plugins folder.
3. Launch server using Aikar flags
4. Scroll down in server log and verify that HorseStats has loaded.  You will see that it enabled and then disabled itself,
5. See error
19:23:03 INFO]: [TabuuCore] Enabling TabuuCore v2.7.0
[19:23:03 INFO]: [TabuuCore] Enabling TabuuCore...
[19:23:03 INFO]: [TabuuCore] TabuuCore enabled.
[19:23:03 INFO]: [Chunky] Enabling Chunky v1.3.92
-->[19:23:03 INFO]: [HorseStats] Enabling HorseStats v1.1
[19:23:03 ERROR]: [HorseStats] Error: Using an older version of TabuuCore than required. Use TabuuCore version 2020.4.5 or higher!
-->[19:23:03 INFO]: [HorseStats] Disabling HorseStats v1.1

**Expected behavior**
I expect the plugin to load and run with the TabuuCore dependency satisfied by the latest version of TabuuCore, which supports Minecraft JE 1.20.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 13.2.1
 - Browser [safari, but N/A]
 - Version [Mac OS 13.2.1, Safari 16.3]

**Smartphone (please complete the following information):**

**Additional context**
The TabuuCore release is only a few hours old.  Apparently HorseStats recognizes it as an older, rather than newer version.

**Comment by MrCrackerplays** [comment]
That's my bad, that issue was already fixed with #1 but it seems I never updated the jar in either the release here on github or on spigotmc.
I currently don't have the time to recompile the plugin but if you know how to compile the plugin yourself you could do that.
Otherwise in case you don't use any other plugins that rely on tabuucore you could for now try and see if [tabuucore version 2020.4.5](https://github.com/Tabuu/TabuuCore/releases/tag/2020.4.5) works for minecraft 1.20.1 but I doubt that

**Comment by TheoLegendSmyth** [comment]
Thx.  I have no idea how to recompile, so I will wait until you repost in the future sometime.  I realize beggars cannot be choosers.   I appreciate you taking the time to respond.

**Comment by MrCrackerplays** [comment]
had some time to test and found some small issues with the newer tabuucore versions so I fixed those and now all should be good with [release v1.2](https://github.com/MrCrackerplays/HorseStats/releases/tag/v1.2) will upload it to spigotmc in a bit

**Comment by TheoLegendSmyth** [comment]
Wow!  I was not expecting such a timely fix.  Thankyou so much!  I loaded v1.2 and it seems to work perfectly. My grandson and I are looking forward to using this to breed the perfect horse!
